### ISSUE TITLE
Gulp - jspm_packages is referenced to a directory above root

### ISSUE THREAD

**Issue by JT-Bruch** [dsebastien/modernWebDevBuild#94] opened 2016-02-05 21:21 UTC
Steps to reproduce:
- install on fresh machine.
- run npm run serve
  - everything works as expected.
- run gulp
 - gets following error.
![image](https://cloud.githubusercontent.com/assets/7430562/12859511/273747ee-cc1c-11e5-8a0b-99b09ffb98a5.png)

This line in vendor.scss needs to be changed to.
@import '../../jspm_packages/github/necolas/normalize.css@3.0.3/normalize.css'; // the path refers to the file at BUILD time

This.
@import '../jspm_packages/github/necolas/normalize.css@3.0.3/normalize.css'; // the path refers to the file at BUILD time

And then everyone is happy. :+1:

**Comment by dsebastien** [comment] 2016-02-09 21:25
Hey @JT-Bruch thanks for the bug report, I'll update the project generator (i.e., https://github.com/dsebastien/modernWebDevGenerator) as that's where the issue is.

**Comment by dsebastien** [comment] 2016-02-09 21:31
I've published 0.3.4 of the generator with the fix: https://www.npmjs.com/package/generator-modern-web-dev

**Comment by dsebastien** [comment] 2016-02-13 12:46
I've found the bug and it was actually in the build: https://github.com/dsebastien/modernWebDevBuild/issues/96

I'm going to create a new minor release of the build and later update the generator.

**Comment by dsebastien** [comment] 2016-02-13 12:54
closed by 0eefaa8

See the release notes: https://github.com/dsebastien/modernWebDevBuild/releases/tag/0.4.0

**Comment by dsebastien** [comment] 2016-02-13 12:55
In your project, you'll have to change the path to stylesheets located in jspm_packages. Also, you'll have to upgrade the dependency of modern-web-dev-build to 0.4.x

**Closed by dsebastien** 2016-02-13 12:54 UTC
